"""Private RIPPLE-GWAS V1 prototype package."""

from ripple.defaults import (
    DEFAULT_LD_SHRINKAGE,
    LD_SHRINKAGE_SENSITIVITY,
    PRIMARY_RESIDUALIZATION_COVARIATES,
    RANK_FRACTION_GRID,
)

__all__ = [
    "DEFAULT_LD_SHRINKAGE",
    "LD_SHRINKAGE_SENSITIVITY",
    "PRIMARY_RESIDUALIZATION_COVARIATES",
    "RANK_FRACTION_GRID",
]
